Run docker commands with third party action

diff --git a/.github/workflows/Unittests.yml b/.github/workflows/Unittests.yml
--- a/.github/workflows/Unittests.yml
+++ b/.github/workflows/Unittests.yml
@@ -42,6 +42,21 @@ jobs:
           build-args: SLURM_TAG=${{ matrix.slurm }}
 
       - name: Run tests
+        uses: addnab/docker-run-action@v3
+        with:
+          image: py-${{ matrix.python }}-${{ matrix.slurm }}
+          options: -v ${{ github.workspace }}:/app
+          run: |
+            # Run tests with coverage and catch the exit status
+            coverage-${{ matrix.python }} run -m unittest discover /app
+            status=$?
+
+            # Generate a coverage report
+            coverage-${{ matrix.python }} report --include="/app/bank/*"
+            coverage-${{ matrix.python }} xml --include="/app/bank/*" -o app/coverage.xml
+            exit $status  # Exit with the appropriate status
+
+      - name: Run tests
         run: docker run -v $(pwd):/app -t py-${{ matrix.python }}-${{ matrix.slurm }} /app/.github/test_with_coverage.sh ${{ matrix.python }}
 
       # Report test coverage to codacy for the python version being tested
